# Generated by Django 3.1.6 on 2021-02-15 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OIA_Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OIAUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=-1, verbose_name='age')),
                ('country', models.CharField(max_length=64, verbose_name='country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='profile')),
            ],
        ),
    ]
