# Generated by Django 3.1.6 on 2021-02-23 18:33

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('OIA_Users', '0002_oiauserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='oiauserprofile',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='student', max_length=16),
        ),
        migrations.AlterField(
            model_name='oiauserprofile',
            name='age',
            field=models.IntegerField(default=None, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='oiauserprofile',
            name='country',
            field=django_countries.fields.CountryField(default=None, max_length=2, null=True, verbose_name='country'),
        ),
    ]
